### ISSUE TITLE
Resolve iplant_groups config

### ISSUE THREAD

**Issue by michael-conway** [angrygoat/DE#10]
see group vars:

```

iplant_groups_docker_repo: diceunc
iplant_groups:
 host: "{{ groups['iplant-groups'][0] }}"
 port: 5080
 base_url: "http://{{ groups['iplant-groups'][0] }}:5080"
 service_name: iplant-groups.service
 service_name_short: iplant-groups
 compose_service: iplant_groups
 service_description: iplant-groups service
 image_name: iplant-groups
 container_name: iplant-groups


```

In docker hub is an iplant-groups and iplant-groups-odum under diceunc.  We forgot why. Why?
